name: Compile Contracts
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[release]')"
    steps:
      - uses: actions/checkout@v2

      - name: Install
        working-directory: ./
        run: yarn install

      - name: Compile
        working-directory: ./
        run: yarn compile

      - name: Set Git Identity
        working-directory: ./
        run: git config --global user.email "engineering@thirdbuy.com" && git config --global user.name "Thirdbuy Engineering"

      - name: Commit
        working-directory: ./
        run: git add -A && git commit -am '[release] compile contracts'

      - name: Version Bump
        working-directory: ./
        run: npm version patch -m "[release] %s"

      - name: Push
        working-directory: ./
        run: git push
